services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: pfe
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python app.py
    depends_on:
      - mysql

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: ./start_streamlit.sh
    depends_on:
      - mysql
